# Generated by Django 5.1.1 on 2025-02-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('recommendation', models.TextField()),
                ('dose', models.CharField(max_length=255)),
                ('features', models.TextField()),
                ('indications', models.TextField()),
            ],
        ),
    ]
