# Generated by Django 5.1.1 on 2025-02-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_medicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dose',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='title',
            field=models.TextField(),
        ),
    ]
