# Generated by Django 5.1.1 on 2025-03-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_medicine_dose_alter_medicine_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
