# Generated by Django 5.1.1 on 2025-03-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_medicine_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
