# Generated by Django 6.0.7 on 2026-07-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_medicine_meta_description_medicine_meta_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicine",
            options={"verbose_name": "Medicine", "verbose_name_plural": "Medicines"},
        ),
    ]
